---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: InstallSystemsSoftware
    inherits: 
    description: 
  fields:
  - execute:
      value: "/Integration/Ansible/Methods/InstallSystemsSoftware"
