---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: InstallSystemsSoftware
    inherits: 
    description: 
  fields:
  - launch:
      value: "/ConfigurationManagement/AnsibleTower/Operations/JobTemplate/InstallSystemsSoftware"
