---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: Install_Application
    inherits: 
    description: 
  fields:
  - job_template_name:
      value: "${/#miq_provision.get_option(:job_template_name)}"
